import sys
import os
from unittest.mock import AsyncMock, MagicMock, patch

# Ensure backend directory is in sys.path
backend_dir = r"c:\Users\ajayr\Downloads\ssodl\skillai\fastapi-auth-module\backend"
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

os.environ["MONGODB_URI"] = "mongodb://localhost:27017/test"
os.environ["JWT_SECRET"] = "super-secret-key-for-test-at-least-32-chars-long"

from fastapi.testclient import TestClient
from main import app
from auth_handler import get_current_admin, get_current_user
from utils.pdf_generator import build_notes_pdf, sanitize_pdf_text

client = TestClient(app)

def make_cursor_mock(items):
    cursor = MagicMock()
    cursor.sort.return_value = cursor
    cursor.skip.return_value = cursor
    cursor.limit.return_value = cursor
    cursor.to_list = AsyncMock(return_value=items)
    return cursor

def test_pdf_generator_binary_validity():
    """Verify that build_notes_pdf produces a valid binary PDF document."""
    sample_note = {
        "title": "Comprehensive Pharmacokinetics & Renal Clearance",
        "topic": "Clinical Pharmacokinetics",
        "subtopic": "Renal Excretion Mechanics",
        "career_field": "Medical & Healthcare",
        "difficulty": "Advanced",
        "summary": "Covers ADME parameters, glomerular filtration, and creatinine clearance titration.",
        "prerequisites": ["Foundations of Human Physiology", "Cellular Biology"],
        "learning_objectives": [
            "Calculate renal clearance rates using Cockcroft-Gault equation",
            "Understand zero-order vs first-order elimination kinetics"
        ],
        "core_concepts": [
            "Glomerular filtration occurs across the semipermeable fenestrated endothelium.",
            "Tubular secretion is an active transport process susceptible to saturation."
        ],
        "technical_breakdown": "Clearance Cl = (U * V) / P where U is urinary concentration, V is flow rate, and P is plasma concentration.",
        "real_world_case_studies": [
            {
                "case_title": "ICU Aminoglycoside Titration in Sepsis",
                "scenario": "A 68-year-old patient with acute kidney injury requires tailored vancomycin dosing.",
                "solution": "Utilize therapeutic drug monitoring (TDM) trough levels and adjust interval from q12h to q24h."
            }
        ],
        "practical_activity": "Perform dosage calculation for a patient with 35 mL/min creatinine clearance.",
        "common_pitfalls": [
            "Assuming serum creatinine alone reflects immediate renal function without factoring age and mass."
        ],
        "key_takeaways": [
            "Renal clearance dictates dosing intervals for hydrophilic drugs.",
            "Always re-evaluate clearance upon changes in fluid balance."
        ],
        "interview_questions": [
            {
                "question": "What is the clinical significance of area under the curve (AUC)?",
                "answer": "AUC represents the total drug exposure over time and guides efficacy and toxicity thresholds."
            }
        ],
        "flashcards": [
            {
                "front": "What defines zero-order elimination?",
                "back": "A constant amount of drug is cleared per unit time regardless of concentration."
            }
        ],
        "practice_quiz": [
            {
                "question": "Which organ is the primary site of drug metabolism?",
                "options": ["Kidneys", "Liver", "Lungs", "Spleen"],
                "correct_answer": "Liver",
                "explanation": "The liver is the principal metabolic factory containing cytochrome P450 enzymes."
            }
        ],
        "next_step": "Proceed to Advanced Pharmacodynamics and Receptor Binding Affinity."
    }

    watermark_config = {
        "text": "SKILLDNA VERIFIED TEST",
        "opacity": 0.12,
        "font_size": 40,
        "rotation": 45,
        "is_enabled": True,
        "color_hex": "#0891b2"
    }

    pdf_bytes = build_notes_pdf(
        note_data=sample_note,
        student_name="Dr. Taylor Smith",
        watermark_settings=watermark_config
    )

    assert isinstance(pdf_bytes, bytes)
    assert len(pdf_bytes) > 2000
    assert pdf_bytes.startswith(b"%PDF-"), "Generated byte sequence must have valid PDF file header"
    print(f"\n[PASS] PDF Generator produced valid {len(pdf_bytes)} bytes PDF stream")

def test_pdf_text_sanitizer():
    """Verify that sanitize_pdf_text escapes XML entities and formats markdown bold/italic."""
    raw = "Formula: A < B & C > D. **Crucial Rule**: Use *italic* values."
    clean = sanitize_pdf_text(raw)
    assert "&lt;" in clean
    assert "&gt;" in clean
    assert "&amp;" in clean
    assert "<b>Crucial Rule</b>" in clean
    assert "<i>italic</i>" in clean
    print("\n[PASS] PDF Text Sanitizer cleanly escaped XML entities and preserved formatting")

def test_admin_watermark_settings_crud():
    """Test retrieving and saving admin PDF watermark configuration."""
    mock_admin = {"email": "admin@skilldna.com", "role": "admin"}
    app.dependency_overrides[get_current_admin] = lambda: mock_admin

    existing_doc = {
        "_id": "mock_wm_id_1",
        "watermark_text": "SKILLDNA AI VERIFIED",
        "font_size": 42,
        "opacity": 0.10,
        "rotation_angle": 45,
        "is_enabled": True,
        "position": "diagonal",
        "color_hex": "#64748b",
        "isDefault": True
    }

    updated_doc = dict(existing_doc)
    updated_doc["watermark_text"] = "SKILLDNA OFFICIAL REVISION"
    updated_doc["opacity"] = 0.15

    with patch("routes.admin_ops.pdf_watermark_settings_collection.find_one", AsyncMock(side_effect=[existing_doc, updated_doc])), \
         patch("routes.admin_ops.pdf_watermark_settings_collection.update_one", AsyncMock(return_value=MagicMock(matched_count=1))):
        
        # 1. Fetch current watermark settings
        get_res = client.get("/api/admin/settings/watermark")
        assert get_res.status_code == 200, f"Expected 200, got {get_res.status_code}"
        data = get_res.json()
        assert data["watermark_text"] == "SKILLDNA AI VERIFIED"
        assert data["opacity"] == 0.10
        print(f"\n[PASS] GET /api/admin/settings/watermark returned: {data['watermark_text']}, opacity={data['opacity']}")

        # 2. Update watermark settings
        payload = {
            "watermark_text": "SKILLDNA OFFICIAL REVISION",
            "font_size": 44,
            "opacity": 0.15,
            "rotation_angle": 35,
            "is_enabled": True,
            "position": "diagonal",
            "color_hex": "#2563eb"
        }
        put_res = client.put("/api/admin/settings/watermark", json=payload)
        assert put_res.status_code == 200, f"Expected 200, got {put_res.status_code}"
        saved = put_res.json()
        assert saved["watermark_text"] == "SKILLDNA OFFICIAL REVISION"
        assert saved["opacity"] == 0.15
        print("\n[PASS] PUT /api/admin/settings/watermark successfully updated database configuration")

    app.dependency_overrides.pop(get_current_admin, None)

def test_learning_pdf_export_endpoint():
    """Test direct POST /api/learning/notes/pdf-export returning streaming binary application/pdf."""
    mock_student = {
        "_id": "mock_student_123",
        "email": "student@university.edu",
        "role": "STUDENT",
        "name": "Jordan Lee"
    }
    app.dependency_overrides[get_current_user] = lambda: mock_student

    note_payload = {
        "topic": "Strategic Talent Acquisition & Sourcing",
        "subtopic": "Passive Candidate Engagement",
        "career_field": "Human Resources",
        "difficulty": "Intermediate",
        "title": "Comprehensive Talent Acquisition Guide",
        "summary": "Methodology for sourcing high-calibre candidates across technical and executive sectors.",
        "prerequisites": ["Fundamentals of HR Management"],
        "learning_objectives": [
            "Formulate Boolean search strings for LinkedIn Recruiter",
            "Establish automated drip campaigns for prospective talent"
        ],
        "core_concepts": [
            "Passive candidates require personalized value propositions rather than standard job descriptions.",
            "Candidate relationship management (CRM) systems track engagement velocity."
        ],
        "technical_breakdown": "Boolean operators AND, OR, NOT, and title modifier syntax (e.g. title:\"VP Engineering\").",
        "real_world_case_studies": [
            {
                "case_title": "FinTech Scaleup Sourcing Sprint",
                "scenario": "Hiring 12 Senior Engineers within 45 days in a competitive market.",
                "solution": "Deployed custom outreach sequences achieving a 42% response rate."
            }
        ],
        "practical_activity": "Draft a 3-touch outreach sequence addressing candidate pain points.",
        "common_pitfalls": ["Sending generic, unpersonalized copy that gets flagged as spam."],
        "key_takeaways": ["Relationship-first outreach drives 3x higher placement efficiency."],
        "interview_questions": [
            {
                "question": "How do you measure sourcing channel effectiveness?",
                "answer": "Track funnel conversion ratios from initial reach-out to technical interview pass rate."
            }
        ],
        "flashcards": [
            {
                "front": "What is time-to-fill?",
                "back": "The total number of days between opening a requisition and candidate job offer acceptance."
            }
        ],
        "practice_quiz": [
            {
                "question": "Which Boolean operator narrows search results by requiring both terms?",
                "options": ["OR", "AND", "NOT", "NEAR"],
                "correct_answer": "AND",
                "explanation": "AND restricts results to documents containing both specified terms."
            }
        ],
        "next_step": "Advance to Executive Compensation Benchmarking and Offer Negotiation."
    }

    mock_wm = {
        "watermark_text": "SKILLDNA VERIFIED",
        "opacity": 0.10,
        "is_enabled": True
    }

    with patch("routes.admin_ops.get_authenticated_user_doc", AsyncMock(return_value=mock_student)), \
         patch("routes.admin_ops.get_active_watermark_dict", AsyncMock(return_value=mock_wm)):
        res = client.post("/api/learning/notes/pdf-export", json=note_payload)
        assert res.status_code == 200, f"Expected 200, got {res.status_code}"
        assert res.headers.get("content-type") == "application/pdf"
        assert "Content-Disposition" in res.headers
        assert res.content.startswith(b"%PDF-")
        print(f"\n[PASS] POST /api/learning/notes/pdf-export returned streaming PDF ({len(res.content)} bytes)")

    app.dependency_overrides.pop(get_current_user, None)

def test_career_twin_progression_pipeline_fields():
    """Verify that Career Twin computes real pipeline milestones and multi-discipline metrics."""
    mock_student = {
        "_id": "mock_student_fin_456",
        "email": "student_corp_fin@firm.com",
        "role": "STUDENT",
        "name": "Morgan Davis",
        "targetCareer": "Corporate Finance",
        "profile": {"targetCareer": "Corporate Finance", "domain": "Finance"}
    }
    app.dependency_overrides[get_current_user] = lambda: mock_student

    mock_profile = {
        "user": "mock_student_fin_456",
        "targetCareer": "Corporate Finance",
        "targetRole": "Financial Analyst",
        "skills": ["Financial Modeling", "Excel"],
        "skillDNA": {"technicalScore": 84}
    }

    with patch("routes.admin_ops.get_authenticated_user_doc", AsyncMock(return_value=mock_student)), \
         patch("routes.admin_ops.profiles_collection.find_one", AsyncMock(return_value=mock_profile)), \
         patch("routes.admin_ops.question_sessions_collection.find", return_value=make_cursor_mock([])), \
         patch("routes.admin_ops.student_answers_collection.find", return_value=make_cursor_mock([])), \
         patch("routes.admin_ops.certificates_collection.find", return_value=make_cursor_mock([])), \
         patch("routes.admin_ops.assessments_collection.find", return_value=make_cursor_mock([])), \
         patch("routes.admin_ops.career_twin_memories_collection.update_one", AsyncMock()):
        
        res = client.get("/api/career-twin/me")
        assert res.status_code == 200, f"Expected 200, got {res.status_code}"
        data = res.json()

        # Core Career Twin keys
        assert "overallScore" in data
        assert "targetRole" in data
        assert "nextRecommendedSkill" in data
        assert "whyRecommended" in data["nextRecommendedSkill"]
        assert "nextBestAction" in data
        assert "structuredPipeline" in data
        assert "practicalProject" in data
        assert "skillEngineTiers" in data

        # Verify 12-milestone pipeline
        pipeline = data["structuredPipeline"]
        assert len(pipeline) == 12, f"Expected 12-step pipeline, got {len(pipeline)}"
        assert pipeline[0]["key"] == "current_position"
        assert pipeline[-1]["key"] == "skill_dna_sync"

        # Verify skill tiers
        tiers = data["skillEngineTiers"]
        assert "beginner" in tiers
        assert "intermediate" in tiers
        assert "advanced" in tiers

        # Verify discipline/career matches
        career = data.get("careerDomain", "") or data.get("targetRole", "")
        assert "Finance" in career or "Financial" in career or "Commerce" in career

        print(f"\n[PASS] GET /api/career-twin/me returned verified 12-step career progression pipeline for field: {career}")
        print(f"       Next Recommended Skill: {data['nextRecommendedSkill']['skill']} ({data['nextRecommendedSkill']['currentLevel']})")
        print(f"       Reason: {data['nextRecommendedSkill']['whyRecommended']}")
        print(f"       Immediate Action: {data['nextBestAction']['title']}")

    app.dependency_overrides.pop(get_current_user, None)

if __name__ == "__main__":
    test_pdf_generator_binary_validity()
    test_pdf_text_sanitizer()
    test_admin_watermark_settings_crud()
    test_learning_pdf_export_endpoint()
    test_career_twin_progression_pipeline_fields()
    print("\n" + "=" * 70)
    print("ALL CAREER, LEARNING & PDF VERIFICATION TESTS PASSED SUCCESSFULLY!")
    print("=" * 70)
